name: Submit Microsoft.PowerToys package to Windows Store

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:

  microsoft_store:
    name: Publish Microsoft Store
    runs-on: ubuntu-latest
    steps:
      # Shouldn't be needed once store-submission is public
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest Version and URL from public releases
        id: releaseVars
        run: |
          release=$(curl https://api.github.com/repos/Microsoft/PowerToys/releases | jq '[.[]|select(.name | contains("Release"))][0]')
          assets=$(jq -n "$release" | jq '.assets')
          whatsNew=$(jq -n "$release" | jq -r '.body')
          powerToysSetup=$(jq -n "$assets" | jq '[.[]|select(.name | contains("PowerToysSetup"))]')
          echo ::set-output name=powerToysInstallerX64Url::$(jq -n "$powerToysSetup" | jq -r '[.[]|select(.name | contains("x64"))][0].browser_download_url')
          echo ::set-output name=powerToysWhatsNew::$(whatsNew)

      - name: Configure Store Credentials
        uses: ./.github/store-submission/
        with:
          command: configure
          type: win32
          seller-id: ${{ secrets.SELLER_ID }}
          product-id: ${{ secrets.PRODUCT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}

      - name: Update draft submission
        uses: ./.github/store-submission/
        with:
          command: update
          product-update: '{
              "packages":[
                  {
                    "packageUrl":"${{ steps.releaseVars.outputs.powerToysInstallerX64Url }}",
                    "languages":["zh-hans", "zh-hant", "en", "cs", "nl", "fr", "pt", "pt-br", "de", "hu", "it", "ja", "ko", "pl", "ru", "es", "tr"],
                    "architectures":["X64"],
                    "installerParameters":"-passive",
                    "isSilentInstall":true
                  }
              ]
            }'

          metadata-update: '{
              "listings": [
                {
                  "language": "en",
                  "description": "Microsoft PowerToys is a set of utilities for power users to tune and streamline their Windows 10 and 11 experience for greater productivity.",
                  "whatsNew": "${{ steps.releaseVars.outputs.powerToysWhatsNew }}",
                  "productFeatures": ["FancyZones", "PowerRename", "Color Picker", "Keyboard Manager", "Shortcut Guide", "PowerToys Run", "Awake", "Image Resizer", "SVG thumbnails", "Markdown file explorer preview pane", "SVG file explorer preview pane", "Find my mouse", "always on top"],
                  "shortDescription": "Microsoft PowerToys is a set of utilities for power users to tune and streamline their Windows 10 experience for greater productivity. For more info on PowerToys overviews and guides, or any other tools and resources for Windows development environments, head over to docs.microsoft.com!",
                  "searchTerms": ["PowerToys", "Fancy Zones", "FancyZones", "PowerRename", "Power Toys", "color picker", "Find my mouse"],
                  "additionalLicenseTerms": "https://aka.ms/powertoys-license"
                }
              ]
            }'
